name: BottledXP
main: BottledXP\Main
version: 1.0.1
api: 5.0.0
author: ZyberPE

commands:
  xpbottle:
    description: Bottle your XP levels
    usage: "/xpbottle <amount>"
    aliases: [xpb]
    permission: bottledxp.use

permissions:
  bottledxp.use:
    default: true
